<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://sncm.anvisa.gov.br/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" name="ContService" targetNamespace="http://sncm.anvisa.gov.br/">
  <wsdl:types>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://sncm.anvisa.gov.br/" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://sncm.anvisa.gov.br/">
  <xs:element name="dataMsg" type="tns:dataMsg"/>
  <xs:complexType name="dataMsg">
    <xs:sequence>
      <xs:element name="dataMsg" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="cont" nillable="true" type="tns:dataMsg"/>
  <xs:element name="contResponse" nillable="true" type="xs:string"/>
</xs:schema>
  </wsdl:types>
  <wsdl:message name="contResponse">
    <wsdl:part element="tns:contResponse" name="contResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="cont">
    <wsdl:part element="tns:cont" name="cont">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="ContService">
    <wsdl:operation name="cont">
      <wsdl:input message="tns:cont" name="cont">
    </wsdl:input>
      <wsdl:output message="tns:contResponse" name="contResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ContServiceSoapBinding" type="tns:ContService">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="cont">
      <soap12:operation soapAction="" style="document"/>
      <wsdl:input name="cont">
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="contResponse">
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ContService">
    <wsdl:port binding="tns:ContServiceSoapBinding" name="ContService">
      <soap12:address location="http://localhost:8080/SNCMRastreamentoService/ContService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
