<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://sncm.anvisa.gov.br/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" name="EventInService" targetNamespace="http://sncm.anvisa.gov.br/">
  <wsdl:types>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://sncm.anvisa.gov.br/" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://sncm.anvisa.gov.br/">
  <xs:element name="dataMsg" type="tns:dataMsg"/>
  <xs:complexType name="dataMsg">
    <xs:sequence>
      <xs:element name="dataMsg" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="evtIn" nillable="true" type="tns:dataMsg"/>
  <xs:element name="evtInResponse" nillable="true" type="xs:string"/>
</xs:schema>
  </wsdl:types>
  <wsdl:message name="evtInResponse">
    <wsdl:part element="tns:evtInResponse" name="evtInResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="evtIn">
    <wsdl:part element="tns:evtIn" name="evtIn">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="EventInService">
    <wsdl:operation name="evtIn">
      <wsdl:input message="tns:evtIn" name="evtIn">
    </wsdl:input>
      <wsdl:output message="tns:evtInResponse" name="evtInResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="EventInServiceSoapBinding" type="tns:EventInService">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="evtIn">
      <soap12:operation soapAction="" style="document"/>
      <wsdl:input name="evtIn">
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="evtInResponse">
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="EventInService">
    <wsdl:port binding="tns:EventInServiceSoapBinding" name="EventInService">
      <soap12:address location="http://localhost:8080/SNCMGerenciadorEventosService/EventInService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
